# Generated by Django 4.1.7 on 2023-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
